[workspace]
members = ["mdsycx", "mdsycx-macro", "website"]
resolver = "2"

[profile.release]
lto = true
opt-level = "s"

[patch.crates-io]
sycamore = { git = "https://github.com/sycamore-rs/sycamore", rev = "0a03d5b" }
