[workspace]
members = ["mdsycx", "mdsycx-macro", "website"]

[patch.crates-io]
sycamore = { git = "https://github.com/sycamore-rs/sycamore", rev = "2a7d015" }

[profile.release]
lto = true
opt-level = "s"
