[package]
name = "website"
edition = "2021"
publish = false

[dependencies]
console_error_panic_hook = "0.1.7"
mdsycx = { path = "../mdsycx" }
sycamore = { version = "0.9.0", features = ["hydrate"] }
wasm-bindgen = "0.2.83"
