[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
mdsycx = { path = "../mdsycx" }
serde = { version = "1.0.144", features = ["derive"] }
sycamore = "0.8.1"
